### ISSUE TITLE
Allow to show which pages have been visited and the log of all requests

### ISSUE THREAD

**Issue by hilnius** [Madumbo/Madumbo-Issues#2] opened 2017-06-19 15:16 UTC
For now, all we know is that there have been "interactions" and "page views", but I'd really like to have a log of what algorithms did : which pages have been visited and which buttons have been triggered.

**Comment by sdeprez** [comment] 2017-06-20 08:32
Hi,

Thanks for your feedback and congratulations for being the first to open an issue (apart us)!

Showing the urls visited is a good idea and we'll likely implement it soon, however showing all the interactions is right now more complicated and (arguably) less useful for the user, but note that the buttons triggered are already shown in the steps to reproduce for bugs that we found.

**Comment by sdeprez** [comment] 2017-08-14 08:27
The urls visited are now available! You can also now filter the errors based on the url they were found.

**Comment by sdeprez** [comment] 2017-08-14 08:28
I'm closing for now since we don't plan to show the interactions done, there are too many of them and it's probably too confusing for the user (click, submit, mouse in, out etc...)

**Closed by sdeprez** 2017-08-14 08:28 UTC
Labels: feature-request
